#!bin/sh

##Illustrates the use of variables

#Special variables

echo "This script was called with $#2 parameters"
echo "The script's name is $@BIN
echo "The arguments are $@="$1""$2"
echo "The first argument is $1
echo "Thhe second argument is $2

#Assigned Variables; Explicit declaration:
MY_VAR='some string'
echo 'the current value of the variable is :' $MY_VAR
echo 
echo 'Please enter aa new string'
read MY_VAR
echo
echo 'the current value of the variable is :'$MY_VAR
echo

##Assigned Variables; Reading (multiple values) from user input
echo 'Enter two numbers seperated by space(s)']
read
echo
echo you entered' $a 'and' $b '; Their sum is:'

## Assigned Variables; Command substition
MY_SUB=$(expr $a +$b)
echo $MY_SUM
